- path: /
  auth: false
  page: ./pages/Welcome

- path: /
  auth: true
  page: ./pages/Places

- path: /foo
  page: ./pages/Foo

- path: /bar/:id
  page: ./pages/Bar

- path: /spam/:id
  page: ./pages/Bar
